development:
  sessions:
    default:
      database: spelling_corrector
      hosts:
        - localhost:27017
      options:
        skip_version_check: true
        safe: true
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
